#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Vite exposes only VITE_-prefixed vars to client bundles, and .env.local is
# already covered by .gitignore's `*.local` pattern (and the explicit
# `.env`/`.env.local`/`.env.*.local` block added alongside this script) — see
# docs/provisioning.md for why each value lives where it does.
ENV_FILE="${ENV_FILE:-.env.local}"

# already_configured KEY: true if KEY already has a non-empty value in
# ENV_FILE. Used to offer skipping steps that create cloud resources, so
# re-running this wizard doesn't produce a second Neon project or a second
# Google OAuth client.
already_configured() {
  local v; v=$(_existing "$1" || true)
  [[ -n "$v" ]]
}

TOTAL_STAGES=5

banner "Litrato Calculator: Neon + Google OAuth provisioning"
note "This wizard only provisions accounts and records credentials. It does"
note "not change any app code — src/App.tsx doesn't read these values yet."
note "See docs/adr/0001-neon-postgres-with-rls.md and"
note "docs/adr/0002-neon-auth-google-only.md for why these choices were made,"
note "and docs/provisioning.md for where every captured value came from."

# ── Stage 1: Neon project + database ───────────────────────────────────────
stage "Neon: create the project and database"
if already_configured NEON_PROJECT_ID && confirm "NEON_PROJECT_ID is already set (from $ENV_FILE) — keep it and skip creating a new Neon project?"; then
  NEON_PROJECT_ID=$(_existing NEON_PROJECT_ID || true)
  say "Keeping the existing Neon project. Skipping creation."
else
  say "We'll create the Neon project that will hold the app's Postgres database."
  open_url "https://console.neon.tech"
  step "Sign in (or create a free Neon account), then click 'New project'."
  step "Name it something like 'litrato-calculator'."
  warn "Pick a region on AWS, not Azure — Neon Auth (ADR-0002) only supports AWS regions."
  step "Accept the default database name, or name it 'litrato' — either is fine."
  step "On the project page, open 'Connection Details' (sometimes 'Connect')."
  step "Copy the full connection string (starts with postgresql://)."
  ask_secret DATABASE_URL "Paste the Neon connection string:"
  step "Find the Project ID — it's in Project settings, or in the URL of this"
  step "console page (console.neon.tech/app/projects/<project-id>)."
  ask NEON_PROJECT_ID "Paste the Neon Project ID:"
  write_env DATABASE_URL "$DATABASE_URL"
  write_env NEON_PROJECT_ID "$NEON_PROJECT_ID"
  note "DATABASE_URL is for a human (or CI) to run migrations by hand — the"
  note "deployed app itself talks to Neon via the Data API below, never with"
  note "this raw connection string, per ADR-0001."
fi

# ── Stage 2: Neon Data API ──────────────────────────────────────────────────
stage "Neon: enable the Data API"
say "The browser reaches Postgres through Neon's Data API, authorizing every"
say "request with the signed-in user's Neon Auth JWT (ADR-0001) — there is no"
say "backend server of our own."
open_url "https://console.neon.tech/app/projects/${NEON_PROJECT_ID:-}"
step "Open the project's 'Data API' settings tab (under Settings, or a top-level"
step "'Data API' tab depending on your Neon dashboard version)."
step "If it shows a toggle, turn Data API on. If it's already on, just copy the URL."
step "Copy the Data API base URL it shows you."
ask VITE_NEON_DATA_API_URL "Paste the Data API base URL:"
write_env VITE_NEON_DATA_API_URL "$VITE_NEON_DATA_API_URL"

# ── Stage 3: Neon Auth — enable Google sign-in ─────────────────────────────
stage "Neon Auth: start enabling Google sign-in"
say "Now we turn on Neon Auth (Better Auth under the hood, per ADR-0002) and"
say "add Google as its only sign-in provider. Neon will show you a redirect"
say "URI (or two — one per environment) that must be registered on a Google"
say "OAuth client. We create that Google client in the next stage, then come"
say "back here afterwards to paste its ID and secret in."
open_url "https://console.neon.tech/app/projects/${NEON_PROJECT_ID:-}"
step "Open the project's 'Auth' tab and click 'Enable Neon Auth' if it isn't already on."
step "Add Google as a sign-in provider (don't finish saving it yet — you don't"
step "have the Google client ID/secret until the next stage)."
step "Neon's Google-provider screen shows the redirect URI(s) to register with"
step "Google. If it shows just one shared URL, use the same value for both"
step "prompts below. If it shows separate ones per environment, copy each."
ask GOOGLE_OAUTH_REDIRECT_URI_LOCAL "Paste the redirect URI to register for local dev:"
ask GOOGLE_OAUTH_REDIRECT_URI_PROD "Paste the redirect URI to register for production:"
step "On the Auth tab (often under 'Configuration' or 'API keys'), copy the"
step "project ID and the publishable client key."
ask VITE_NEON_AUTH_PROJECT_ID "Paste the Neon Auth project ID:"
ask VITE_NEON_AUTH_PUBLISHABLE_KEY "Paste the Neon Auth publishable client key:"
note "If the same screen also shows a secret/server key, grab that too — it's"
note "not read by any app code today, but recording it now saves a second trip"
note "when a later ticket needs it. Press Enter to leave it blank if you don't"
note "see one (dashboard labels vary across Neon Auth's beta versions)."
ask_secret NEON_AUTH_SECRET_KEY "Paste the Neon Auth secret/server key (optional):"
write_env GOOGLE_OAUTH_REDIRECT_URI_LOCAL "$GOOGLE_OAUTH_REDIRECT_URI_LOCAL"
write_env GOOGLE_OAUTH_REDIRECT_URI_PROD "$GOOGLE_OAUTH_REDIRECT_URI_PROD"
write_env VITE_NEON_AUTH_PROJECT_ID "$VITE_NEON_AUTH_PROJECT_ID"
write_env VITE_NEON_AUTH_PUBLISHABLE_KEY "$VITE_NEON_AUTH_PUBLISHABLE_KEY"
[[ -n "$NEON_AUTH_SECRET_KEY" ]] && write_env NEON_AUTH_SECRET_KEY "$NEON_AUTH_SECRET_KEY"

# ── Stage 4: Google Cloud OAuth client ─────────────────────────────────────
stage "Google Cloud: register the OAuth client"
if already_configured GOOGLE_OAUTH_CLIENT_ID && confirm "GOOGLE_OAUTH_CLIENT_ID is already set — keep it and skip creating a new Google OAuth client?"; then
  GOOGLE_OAUTH_CLIENT_ID=$(_existing GOOGLE_OAUTH_CLIENT_ID || true)
  GOOGLE_OAUTH_CLIENT_SECRET=$(_existing GOOGLE_OAUTH_CLIENT_SECRET || true)
  say "Keeping the existing Google OAuth client. Skipping creation."
else
  open_url "https://console.cloud.google.com/apis/credentials"
  step "Pick or create a Google Cloud project for this app."
  step "If prompted, configure the OAuth consent screen first: External user"
  step "type, app name 'Litrato Calculator', your email as support/developer contact."
  step "Back on Credentials, click 'Create credentials' → 'OAuth client ID'."
  step "Application type: 'Web application'. Name it 'Litrato Calculator'."
  step "Under 'Authorized redirect URIs', add both:"
  say "    - ${GOOGLE_OAUTH_REDIRECT_URI_LOCAL:-<local redirect URI from the previous stage>}"
  say "    - ${GOOGLE_OAUTH_REDIRECT_URI_PROD:-<production redirect URI from the previous stage>}"
  step "Under 'Authorized JavaScript origins', add http://localhost:5173 and"
  step "https://litrato-calculator.vercel.app"
  step "Click 'Create'. Copy the Client ID shown."
  ask GOOGLE_OAUTH_CLIENT_ID "Paste the Google OAuth Client ID:"
  step "Copy the Client secret shown next to it."
  ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste the Google OAuth Client secret:"
  write_env GOOGLE_OAUTH_CLIENT_ID "$GOOGLE_OAUTH_CLIENT_ID"
  write_env GOOGLE_OAUTH_CLIENT_SECRET "$GOOGLE_OAUTH_CLIENT_SECRET"
fi

# ── Stage 5: Wire the Google credentials back into Neon Auth ──────────────
stage "Neon Auth: finish wiring the Google credentials"
if confirm "Has Google sign-in already been saved and tested working in Neon Auth before?"; then
  say "Skipping — nothing left to wire up."
else
  open_url "https://console.neon.tech/app/projects/${NEON_PROJECT_ID:-}"
  step "Back on the Auth tab's Google provider form, paste in:"
  say "    - Client ID: ${GOOGLE_OAUTH_CLIENT_ID:-<paste from the previous stage>}"
  say "    - Client secret: (from the previous stage — hidden above, still in $ENV_FILE)"
  step "Save. Neon Auth's Google sign-in is now fully configured."
  step "If Neon's dashboard offers a 'test sign-in' link, use it once to confirm"
  step "the redirect URIs were entered correctly on both sides."
fi

finish
say "Next: a later ticket wires src/App.tsx up to these values (VITE_-prefixed"
say "ones are safe to expose to the browser; the rest are for migrations,"
say "rotation, and admin tooling only — never commit $ENV_FILE)."
